#!/bin/bash
cd /home/POS/Desktop/POS-Project/api || { echo "Failed to change directory" > ~/pos_project.log; exit 1; }
npx nodemon server.js >> ~/pos_project.log 2>&1
echo "Script ended" >> ~/pos_project.log


#!/bin/bash
cd /home/POS/Desktop/POS-Project/web/app || { echo "Failed to change directory" >> ~/pos_project_NPM.log; exit 1; }
npm start >> ~/pos_project_NPM.log 2>&1
echo "Script ended" >> ~/pos_project_NPM.log

#!/bin/bash

LOGFILE=~/pos_project_website.log

# Start logging
echo "Starting script..." | tee -a $LOGFILE

# Wait 10 seconds to ensure the system is fully up
sleep 10

# Open Chromium browser and navigate to localhost:3000 in full screen mode
echo "Opening Chromium browser..." | tee -a $LOGFILE
chromium-browser --start-fullscreen http://localhost:3000 >> $LOGFILE 2>&1

# End logging
echo "Script ended" | tee -a $LOGFILE
